"""DB 接続とスキーマ。DESIGN.md §3 をそのまま実装する。

- 既定は SQLite（data/sc.db）。ローカル学習用
- DATABASE_URL（postgres://...）があれば Postgres。Vercel では永続ディスクがないのでこちらを使う
どちらでも同じ SQL が通るように、プレースホルダは ? で書き、Postgres では %s に変換する。
"""
from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator

from .config import DB_PATH

DATABASE_URL = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL") or ""
IS_PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))


def _schema(pg: bool) -> list[str]:
    pk = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if pg else "INTEGER PRIMARY KEY"
    return [
        f"""CREATE TABLE IF NOT EXISTS miss (
  id           {pk},
  subject      TEXT NOT NULL,
  field        TEXT,
  question     TEXT NOT NULL,
  correct      TEXT NOT NULL,
  chose        TEXT,
  why          TEXT,
  source       TEXT,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)""",
        f"""CREATE TABLE IF NOT EXISTS card (
  id           {pk},
  miss_id      INTEGER REFERENCES miss(id) ON DELETE CASCADE,
  front        TEXT NOT NULL,
  back         TEXT,
  tags         TEXT,
  due          TIMESTAMP NOT NULL,
  stability    REAL,
  difficulty   REAL,
  state        INTEGER,
  step         INTEGER,
  last_review  TIMESTAMP
)""",
        f"""CREATE TABLE IF NOT EXISTS review_log (
  id          {pk},
  card_id     INTEGER REFERENCES card(id) ON DELETE CASCADE,
  rating      INTEGER NOT NULL,
  reviewed_at TIMESTAMP NOT NULL,
  elapsed_ms  INTEGER
)""",
        f"""CREATE TABLE IF NOT EXISTS kamoku_b_question (
  id          {pk},
  exam        TEXT NOT NULL,
  qno         INTEGER NOT NULL,
  theme       TEXT,
  qs_pdf      TEXT NOT NULL,
  qs_pages    TEXT,
  ans_md      TEXT,
  cmnt_md     TEXT,
  UNIQUE(exam, qno)
)""",
        f"""CREATE TABLE IF NOT EXISTS attempt (
  id           {pk},
  question_id  INTEGER REFERENCES kamoku_b_question(id),
  body         TEXT NOT NULL,
  diagram_mmd  TEXT,
  minutes      INTEGER,
  submitted_at TIMESTAMP,
  revealed     BOOLEAN DEFAULT FALSE
)""",
        f"""CREATE TABLE IF NOT EXISTS grade (
  id           {pk},
  attempt_id   INTEGER REFERENCES attempt(id) ON DELETE CASCADE,
  detail       TEXT NOT NULL,
  score_pct    INTEGER,
  next_fix     TEXT NOT NULL,
  graded_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)""",
        f"""CREATE TABLE IF NOT EXISTS weakness (
  id           {pk},
  label        TEXT NOT NULL UNIQUE,
  count        INTEGER DEFAULT 1,
  last_seen    TIMESTAMP,
  resolved     BOOLEAN DEFAULT FALSE,
  clean_streak INTEGER DEFAULT 0
)""",
    ]


# DESIGN.md §3 「weakness の初期データ（投入必須）」。空テーブルから始めない。
WEAKNESS_SEED = [
    "設問の語尾と答えの形が対応していない",
    "字数超過（多くの設問は20〜40字）",
    "開発プロセスを問われて運用プロセスの対策に逃げる",
    "問題文中の固有名詞を使わず一般名詞で答える",
    "攻撃手法名だけを書いて成立条件や影響を書かない",
]


class Row(dict):
    """名前でも位置でも引ける行。sqlite3.Row と同じ使い方ができる。"""

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class Cursor:
    def __init__(self, cur: Any, pg: bool) -> None:
        self._cur = cur
        self._pg = pg

    def _rows(self, rows: Any) -> list[Row]:
        cols = [d[0] for d in self._cur.description]
        return [Row(zip(cols, r)) for r in rows]

    def fetchone(self) -> Row | None:
        r = self._cur.fetchone()
        return None if r is None else self._rows([r])[0]

    def fetchall(self) -> list[Row]:
        return self._rows(self._cur.fetchall())

    @property
    def lastrowid(self) -> int | None:  # sqlite のみ。PG は RETURNING id を使う
        return getattr(self._cur, "lastrowid", None)


class Connection:
    """sqlite3 / psycopg を同じ顔で扱う薄いラッパー。"""

    def __init__(self, raw: Any, pg: bool) -> None:
        self._raw = raw
        self.pg = pg

    def execute(self, sql: str, params: tuple | list = ()) -> Cursor:
        if self.pg:
            sql = sql.replace("?", "%s")
            cur = self._raw.cursor()
            cur.execute(sql, tuple(params))
            return Cursor(cur, True)
        return Cursor(self._raw.execute(sql, tuple(params)), False)

    def insert(self, sql: str, params: tuple | list = ()) -> int:
        """INSERT して新しい id を返す。sql には RETURNING を書かないこと。"""
        cur = self.execute(sql + " RETURNING id", params)
        row = cur.fetchone()
        return int(row[0]) if row else 0

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def connect() -> Connection:
    if IS_PG:
        import psycopg

        return Connection(psycopg.connect(DATABASE_URL, connect_timeout=10), True)
    raw = sqlite3.connect(DB_PATH, check_same_thread=False)
    raw.execute("PRAGMA foreign_keys = ON")
    return Connection(raw, False)


@contextmanager
def get_db() -> Iterator[Connection]:
    conn = connect()
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def backend_name() -> str:
    return "postgres" if IS_PG else "sqlite"


def init_db() -> None:
    with get_db() as conn:
        for stmt in _schema(conn.pg):
            conn.execute(stmt)
        for label in WEAKNESS_SEED:
            conn.execute(
                "INSERT INTO weakness(label, count, last_seen) VALUES (?, 0, NULL) ON CONFLICT(label) DO NOTHING",
                (label,),
            )


if __name__ == "__main__":
    init_db()
    print(f"initialized ({backend_name()})")
